### ISSUE TITLE
Vijanden gaan veel te snel

### ISSUE THREAD

**Issue by The-creeper-cow** [Zwengel/PythonGame#3]
ik zou graag willen dat de snelheid een beetje omlaag ging ik wou het zelf doen maar kon het nergens vinden

vroeger gingen ze veel langzamer

**Comment by wb9688** [comment]
That's because your computer is too fast.

**Comment by wb9688** [comment]
You can change the speed of the badger by changing the following line:

```
badguy[0]-=7
```
